version: "3.8"

services:
  php:
    build:
      context: ./
    volumes:
      - "./:/var/www/api"
    restart: unless-stopped

  server:
    restart: unless-stopped
    image: nginx:1.17-alpine
    ports:
      - "5001:80"
    volumes:
      - ./:/var/www/api
      - ./php.conf:/etc/nginx/conf.d/default.conf